---
plugin: aws_ec2
regions:
  - us-east-2
keyed_groups:
  - key: tags.Name
  - key: tags.Group
filters:
  instance-state-name : running
compose:
  ansible_host: public_ip_address
hostnames:
  - tag:Name=Master  
include_filters:
- tag:Name:
  - 'Master'  
