version: '3.2'

services:
  db1:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #networks:
    #  - gate
    ports:
      - "3306:3306"
    deploy:
      mode: replicated
      replicas: 5  
  java1:
    container_name: java1
    build:
      context: ./java/docker-tomcat-tutorial/
    ports:
      - "8080:8080"    
    restart: always
    #networks:
    #  - gate
    depends_on:
      - db1
    deploy:
      mode: replicated
      replicas: 5   
  web1:
    container_name: web1
    build:
      context: ./first_image
    ports:
      - "80:80"    
    restart: always
    #networks:
    #  - gate
    depends_on:
      - java1
    deploy:
      mode: replicated
      replicas: 5     

volumes:
  db_data:

networks:
  gate:
    driver: bridge
