version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    #depends_on:
    #  - jenkins
    #links:
    #  - jenkins 
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    networks:
      - app-network
    ports:
      - 8083:8080
      - 50003:50000
    container_name: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

#Docker Networks
networks:
  app-network:
    driver: bridge