---

- hosts: aws
  #remote_user: myuser
  become: true
  tasks:
  - name: Performing Tasks for Debian
    include: ubuntu.yml
    when: ansible_os_family == 'Debian'
  - name: Performing Tasks for RedHat
    include: centos.yml
    when: ansible_os_family == 'RedHat'
  #- name: Performing Tasks for CentOS
  #  include_tasks: centos.yml
  #  when: ansible_facts['distribution'] == 'CentOS'  "ansible_os_family": "RedHat"
  #- name: Performing Tasks for Ubuntu
  #  include_tasks: ubuntu.yml
  #  when: ansible_facts['distribution'] == 'Ubuntu' "ansible_os_family": "Debian"

  