---

- hosts: aws
  #remote_user: myuser
  become: true
  tasks:
  - name: Performing Tasks for Debian
    include: ubuntu.yml
    when: ansible_os_family == 'Debian'
  - name: Performing Tasks for RedHat
    include: centos.yml
    when: ansible_os_family == 'RedHat'
  

  