---

- hosts: all
  become: true
  vars:
    docker_compose_version: "1.29.2"
  tasks:
  - name: Performing Tasks for Debian
    include: ubuntu.yaml
    when: ansible_os_family == 'Debian'
  - name: Performing Tasks for RedHat
    include: centos.yaml
    when: ansible_os_family == 'RedHat'
  
